### ISSUE TITLE
Implement TestMethodWithoutTestAttribute

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#278]
Certain testing frameworks require the testing class to have an attribute (like `[TestClass]`). For these classes we can display a warning when there is a `public` method in it without the appropriate testing attribute. Helper methods should be private anyway.

One scenario I can think of however is a nested class with public members to get/calculate/whatever some testing data. Maybe we can look for assertions in the method body? I don't think we can ignore nested classes outright since I've seen people group tests that way.

**Comment by Hosch250** [comment]
Do/should all tests from all frameworks use `Assert.Whatever()` to determine when a test passes or fails?  Are all tests `void`?  If so, we can mostly mitigate the issue of calculating/getting data from public members.  Some, of course, could be general setup methods, so...

**Comment by Vannevelj** [comment]
No, we can't rely on either of these things. There are fluent APIs and async tests (that use `Task` return type) which would cause too many false alarms. What we could do is exclude all public methods that either have a non-`Task`/`Task<T>` return type or that have a known attribute like `[SetupMethod]`.

**Comment by Hosch250** [comment]
Visual Studio's built-in test framework methods are `void`.

**Comment by Vannevelj** [comment]
Not necessarily -- you can use `Task` as well if you have an `async` test method.

**Comment by Hosch250** [comment]
I just meant that we couldn't just ensure that the return type is `Task` or `Task<T>`

**Comment by Vannevelj** [comment]
Right. So we can just trigger the warning on every `public` method in a unit test class (`[TestClass]`, `[TestFixture], etc)` that has a non-`void` and non-`Task` return type and does not contain any of these special test attributes like `[SetupMethod]`
