### ISSUE TITLE
Disable VSD0012 by default?

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#294]
Catching all exceptions with `catch(Exception)` is commonly done. While it would be more 'correct' to specifically catch the expected exceptions, sometimes you just want to handle all of them in the same manner anyway.

I feel like the more pragmatic approach would be to disable this analyzer by default and allow users to enable it if they should wish so.

**Comment by Hosch250** [comment]
Would it be possible to ask users if they wanted it on or off when VSD was first installed?  If I just installed VSD from NuGet, I probably wouldn't even bother checking if any were disabled because I would expect it to be enabled by default.

**Comment by Vannevelj** [comment]
As an extension: maybe, I don't know. As a NuGet package: I don't think you can actually interact with the user but this shouldn't happen anyway -- we're not going to ask them about every analyzer either. Perhaps just leave it activated as it is now..
