### ISSUE TITLE
Implement ImplementEqualsAndHashcode

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#477]
Provide a basic implementation. This should work as a context action when the caret is on the class declaration. Related to #185 and #3

https://msdn.microsoft.com/en-us/library/336aedhh(v=vs.71).aspx

**Comment by Vannevelj** [comment]
Consider https://msdn.microsoft.com/en-us/library/ms173147(v=vs.90).aspx for a better example implementation. Take note of these things too: http://codereview.stackexchange.com/a/122490/21028

**Comment by Hosch250** [comment]
You can compute the hash code from fields that are not mutable; or

You can ensure that the hash code of a mutable object does not change while the object is contained in a collection that relies on its hash code.

Otherwise, you might think that the mutable object is lost in the hash table. If you do choose to override GetHashCode for a mutable reference type, your documentation should make it clear that users of your type should not modify object values while the object is stored in a hash table.

https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx

**Comment by Vannevelj** [comment]
Okay, following that advice we have to make sure that we only use immutable fields in GetHashcode().

This means:

* All value types (if a value type is mutable we have -- or will have -- analyzers that warn for that)
* All reference types that are `const` or `readonly`

**Comment by Vannevelj** [comment]
Following the brainstorming over at http://programmers.stackexchange.com/q/317576/82513 this is the result:

* Fields marked with `readonly`
* Properties that have no getter 
* The type must always be a struct (classes not allowed)
* The field/property cannot be static
* Exception: `string` is allowed as well

You can already get a lot of sidecases by combining some of these rules. Additionally:
* If there are no eligible fields, return `0` as hashcode
* If the type is an interface, we ignore it as well
* Also add a test with a `delegate` (I don't know if that gets picked up as a field)

Furthermore: 
* Add a comment into the generated `GetHashCode()` that says something along the lines of `// Add any fields you're interested in, taking into account the guidelines as described in https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx`

**Comment by JohanLarsson** [comment]
> The type must always be a struct (classes not allowed)
What is the reason for this? `System.String` is a reference type that has value semantics.

**Comment by Vannevelj** [comment]
@JohanLarsson referencing the programmers.se post mentioned above:

> Since it would be very not feasible to detect if a class is immutable, we should probably eliminate that entirely aside from `string` perhaps.

Structs are (should?) be immutable so once we have our `struct` field, that hashcode will never change. However if we have a `class` field then we should only do this for those we can prove to be immutable which is a really hard task (or impossible when you consider external types).
The one exception we allow here are strings because they're so common and we know them to be immutable.

We could allow classes to this and assume that everyone implements the hashcodes on their custom types properly (e.g. follows these rules all the way down the composition chain) but I think it's safe to say that's not the case so for this auto-implementation we ignore those classes altogether.

**Comment by JohanLarsson** [comment]
Ok I read it wrong, thought it was filtering out suggesting to generate equality for reference types.

Regarding what members to include value types and strings probably make sense.

About not trusting the equality implementation: 
1) There is no guarantee it is correctly implemented for a struct, sample:
```c#
public struct MyStruct : IEquatable<MyStruct>
{
    public readonly string Text;

    public MyStruct(string text)
    {
        this.Text = text;
    }

    public bool Equals(MyStruct other)
    {
        return string.Equals(this.Text, other.Text, StringComparison.OrdinalIgnoreCase);
    }

    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        return obj is MyStruct && this.Equals((MyStruct)obj);
    }

    public override int GetHashCode()
    {
        return this.Text.GetHashCode();
    }
}
```

2) We rely on the implementation in other places such as if we use it in dictionaries or sets so trusting it here makes sense imo.

In the future it is potentially an idea to have a hidden analyzer for all immutable members that shows a lightbulb 'Include in equality' It will be tricky code gen to add it to an existing equality & hashcode implementation.

R# has a nice dialog for generating equality.
