### ISSUE TITLE
NonEncapsulatedOrMutableField does not work for static fields

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#546]
This should have triggered but it didn't:

    public static string ReferenceFile = "reference_primes_up_to_64k.txt";

**Comment by Hosch250** [comment]
No repro here.

**Comment by Vannevelj** [comment]
Really? I checked it with http://codereview.stackexchange.com/q/127024/21028 and it didn't show any warnings. I didn't look at it in an isolated scenario though

**Comment by Hosch250** [comment]
Minimal repro:

    public class ReferencePrimesUpTo64K
    {
        public static string ReferenceFile = "reference_primes_up_to_64k.txt";
        
        static ReferencePrimesUpTo64K()
        {
            if (!System.IO.File.Exists(ReferenceFile))
            {
            }
        }
    }

**Comment by Hosch250** [comment]
This also reproduces it:

    public class ReferencePrimesUpTo64K
    {
        public string ReferenceFile = "reference_primes_up_to_64k.txt";

        public void Bar() => Foo(ReferenceFile);

        private void Foo(string ee)
        {
            ee = "t";
            ee = "t";
        }
    }
