### ISSUE TITLE
OnPropertyChangedWithoutCallerMemberName bug

### ISSUE THREAD

**Issue by Hosch250** [VSDiagnostics/VSDiagnostics#553]
On the following lines, there is a null reference exception:

    var parentClass = methodDeclaration.Ancestors().OfType<ClassDeclarationSyntax>(SyntaxKind.ClassDeclaration).FirstOrDefault();
    var typeSymbol = context.SemanticModel.GetDeclaredSymbol(parentClass);

This issue can be duplicated with the following code:

```
struct Foo
{
    public override string ToString() { return string.Empty; }
}
```

The issue is, of course, that the parent is not in a class.  This should probably be fixed by working off the class declaration and iterating over those members that are of `SyntaxKind.MethodDeclaration`.

**Comment by Vannevelj** [comment]
Resolved by allowing structs as well as classes.
