### ISSUE TITLE
LoopedRandomInstantion with structs

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#577]
Right now it seems like we're not account for this to happen in a struct. Concerns this line at https://github.com/VSDiagnostics/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/LoopedRandomInstantiation/LoopedRandomInstantiationAnalyzer.cs#L45:

    while (!currentNode.IsKind(SyntaxKind.ClassDeclaration))

**Comment by Hosch250** [comment]
The problem there is that it just will not early-exit for struct--it will keep climbing the tree right up to the compilation syntax and crash when the node is null.
