### ISSUE TITLE
Installing VSDiagnostics-Nuget in a project adds Microsoft.CodeAnalysis.* Nugets/References

### ISSUE THREAD

**Issue by donid** [VSDiagnostics/VSDiagnostics#584]
Hi!
When i install VSDiagnostics in my project via NuGet, it adds several Microsoft.CodeAnalysis.\* NuGet packages and their dependencies to the project. This is annoying, because you can't distinguish which package is needed by the project and which is needed by the VSDiagnostics-analyzers. The same problem appears in the 'References' node of the Solution-Explorer: the dependencies of VSDiagnostics are child nodes of 'References' and not children of 'Analyzers'. Other analyzers (Wintellect.Analyzers, RefactoringEssentials and so on) don't show this behavior i.e. they don't add dependencies. So, why does VSDiagnostics add them?

**Comment by Vannevelj** [comment]
Hey @donid 

Thanks for bringing this to my attention. I will look into it whether it is necessary or not and get back to you soon. I'm not entirely sure myself to be honest -- it could be that it can be omitted.

**Comment by Vannevelj** [comment]
I'll remove the dependencies in the next release and try to speed up the release. You should be able to manually remove them though.
