### ISSUE TITLE
Make SingleCatchAllException opt-in

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#594]
Catch all exceptions aren't all that bad. I think we should disable it by default and let people enable it if they want it.

**Comment by Hosch250** [comment]
Perhaps a Hidden would be good?  No marker, and only available when the cursor is on the `catch` token?

**Comment by Vannevelj** [comment]
There's no code fix, just an analyzer. Does anything happen at all then if you make it hidden?

**Comment by Hosch250** [comment]
I don't think so, but I can't say for sure.

**Comment by Vannevelj** [comment]
closed in #597
