### ISSUE TITLE
TypeToVar with dynamic variable

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#600]
Test TypeToVar with this:

    dynamic exceptionInfo = new ExpandoObject();

**Comment by Hosch250** [comment]
`dynamic e = new ExpandoObject();` does not trigger this exception, nor do any other `dynamic` variable.  `ExpandoObject e = new ExpandoObject();` triggers this and results in `var e = new ExpandoObject();`.

**Comment by Vannevelj** [comment]
Do we have tests for this?

**Comment by Hosch250** [comment]
No, we do not.  I can add them later.

**Comment by Vannevelj** [comment]
That'd be great, cheers
