### ISSUE TITLE
Crash in SimplifyExpressionBodiedMemberCodeFix

### ISSUE THREAD

**Issue by Hosch250** [VSDiagnostics/VSDiagnostics#608]
The following crashes the code fix because there is a statement, but no expression.  The fix, I think, would be to not fire the expression on `void` methods.

    void Foo()
    {
        return;
    }

**Comment by Vannevelj** [comment]
I haven't looked at the code but surely that's not the right solution -- it would eliminate all `void` methods from the analyzer. I'm certain the code can be adapted to account for this edge case
