### ISSUE TITLE
bool? == true can't be simplified

### ISSUE THREAD

**Issue by Vannevelj** [VSDiagnostics/VSDiagnostics#612]
Verify that the `== true` simplifier doesn't fire for nullable bools.

**Comment by Hosch250** [comment]
We already have a test for this:
https://github.com/VSDiagnostics/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToTrueLiteralTests.cs#L595
https://github.com/VSDiagnostics/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToFalseLiteralTests.cs#L506

**Comment by Hosch250** [comment]
We should make an issue for merging these two analyzers, however.

**Comment by Vannevelj** [comment]
Perhaps they should've been but it's not an important enough issue to change now
